name: Build, Test, and Upload Artifact

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Build with Hatch
        run: hatch build

      - name: Test with Hatch
        run: hatch test
        env:
          COVERAGE_FILE: .coverage.3.13
          PYTHON: 3.13

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-3.13
          path: dist/
          if-no-files-found: error
